// Generated by typings
// Source: .typings/react-side-effect.d.ts
declare module 'react-side-effect' {
  function withSideEffect(
    reducePropsToState : Function,
    handleStateChangeOnClient : Function, 
    mapStateOnServer? : Function
  ): <T>(c: T) => T;

  export = withSideEffect;
}
